import { getImage } from "./helpers";
import { FOOD_CATEGORIES } from "./constants.js";

export const FOOD = [
	// breakfast
	{
		id: 1,
		name: "Pancakes",
		price: 5.99,
		image: getImage("pancakes"),
		description: "Fluffy pancakes with syrup and berries.",
		category: FOOD_CATEGORIES.BREAKFAST,
	},
	{
		id: 2,
		name: "Omelette",
		price: 4.49,
		image: getImage("omelette"),
		description: "Three-egg omelette with veggies and cheese.",
		category: FOOD_CATEGORIES.BREAKFAST,
	},
	{
		id: 3,
		name: "Avocado Toast",
		price: 6.29,
		image: getImage("avocado-toast"),
		description: "Toasted sourdough topped with smashed avocado.",
		category: FOOD_CATEGORIES.BREAKFAST,
	},
	{
		id: 4,
		name: "Waffles",
		price: 5.89,
		image: getImage("waffles"),
		description: "Golden waffles with whipped cream and fruits.",
		category: FOOD_CATEGORIES.BREAKFAST,
	},
	{
		id: 5,
		name: "Bagel & Cream Cheese",
		price: 3.99,
		image: getImage("bagel"),
		description: "Toasted bagel with cream cheese.",
		category: FOOD_CATEGORIES.BREAKFAST,
	},
	{
		id: 6,
		name: "Granola Bowl",
		price: 5.49,
		image: getImage("granola"),
		description: "Greek yogurt, granola, and fresh berries.",
		category: FOOD_CATEGORIES.BREAKFAST,
	},
	{
		id: 7,
		name: "Breakfast Burrito",
		price: 6.99,
		image: getImage("breakfast-burrito"),
		description: "Eggs, cheese, and sausage wrapped in a tortilla.",
		category: FOOD_CATEGORIES.BREAKFAST,
	},
	{
		id: 8,
		name: "French Toast",
		price: 5.79,
		image: getImage("french-toast"),
		description: "Classic French toast with powdered sugar.",
		category: FOOD_CATEGORIES.BREAKFAST,
	},
	{
		id: 9,
		name: "Fruit Platter",
		price: 4.99,
		image: getImage("fruit-platter"),
		description: "Seasonal fruits served chilled.",
		category: FOOD_CATEGORIES.BREAKFAST,
	},

	// lunch
	{
		id: 10,
		name: "Cheese Pizza",
		price: 8.99,
		image: getImage("pizza"),
		description: "Classic cheese pizza with tomato sauce.",
		category: FOOD_CATEGORIES.LAUNCH,
	},
	{
		id: 11,
		name: "Caesar Salad",
		price: 7.49,
		image: getImage("caesar-salad"),
		description: "Romaine, parmesan, croutons, and Caesar dressing.",
		category: FOOD_CATEGORIES.LAUNCH,
	},
	{
		id: 12,
		name: "Club Sandwich",
		price: 6.99,
		image: getImage("club-sandwich"),
		description: "Turkey, bacon, lettuce, and tomato on toast.",
		category: FOOD_CATEGORIES.LAUNCH,
	},
	{
		id: 13,
		name: "Chicken Wrap",
		price: 7.29,
		image: getImage("chicken-wrap"),
		description: "Grilled chicken wrap with fresh veggies.",
		category: FOOD_CATEGORIES.LAUNCH,
	},
	{
		id: 14,
		name: "Burger",
		price: 9.49,
		image: getImage("burger"),
		description: "Beef burger with lettuce, tomato, and cheese.",
		category: FOOD_CATEGORIES.LAUNCH,
	},
	{
		id: 15,
		name: "Grilled Cheese",
		price: 4.99,
		image: getImage("grilled-cheese"),
		description: "Melted cheese sandwich on sourdough.",
		category: FOOD_CATEGORIES.LAUNCH,
	},
	{
		id: 16,
		name: "Tuna Salad",
		price: 6.79,
		image: getImage("tuna-salad"),
		description: "Tuna, mayo, celery, and greens.",
		category: FOOD_CATEGORIES.LAUNCH,
	},
	{
		id: 17,
		name: "Roasted Boar Feast",
		price: 12.99,
		image: getImage("roasted-boar-feast"),
		description: "Succulent wild boar roasted over an open flame, served with root vegetables and dark rye bread.",
		category: FOOD_CATEGORIES.LAUNCH,
	},
	{
		id: 18,
		name: "Root Harvest Bowl",
		price: 9.49,
		image: getImage("root-harvest-bowl"),
		description:
			"A warm bowl of roasted carrots, parsnips, beets, and turnips, drizzled with honey-thyme glaze and served with barley.",
		category: FOOD_CATEGORIES.LAUNCH,
	},

	// dinner
	{
		id: 19,
		name: "Smoked Venison Stew",
		price: 14.99,
		image: getImage("venison-stew"),
		description: "Slow-cooked venison with root vegetables and herbs, served in a wooden bowl.",
		category: FOOD_CATEGORIES.DINNER,
	},
	{
		id: 20,
		name: "Grilled Fjord Salmon",
		price: 13.49,
		image: getImage("fjord-salmon"),
		description: "Freshly caught salmon from the icy fjords, grilled over open flame.",
		category: FOOD_CATEGORIES.DINNER,
	},
	{
		id: 21,
		name: "Roasted Boar Shank",
		price: 16.99,
		image: getImage("boar-shank"),
		description: "A massive shank of wild boar, roasted with juniper and garlic.",
		category: FOOD_CATEGORIES.DINNER,
	},
	{
		id: 22,
		name: "Herbed Barley & Mushrooms",
		price: 9.89,
		image: getImage("barley-mushrooms"),
		description: "Earthy barley with foraged mushrooms and fresh herbs from the north.",
		category: FOOD_CATEGORIES.DINNER,
	},
	{
		id: 23,
		name: "Honey-Glazed Carrots & Parsnips",
		price: 8.49,
		image: getImage("honey-root-veg"),
		description: "Sweet root vegetables roasted in a honey and thyme glaze.",
		category: FOOD_CATEGORIES.DINNER,
	},
	{
		id: 24,
		name: "Seafarer's Fish Pie",
		price: 11.49,
		image: getImage("fish-pie"),
		description: "Flaky fish baked in a spiced root-vegetable crust, inspired by Viking voyages.",
		category: FOOD_CATEGORIES.DINNER,
	},
	{
		id: 25,
		name: "Leg of Lamb with Juniper Berries",
		price: 15.49,
		image: getImage("juniper-lamb"),
		description: "Tender lamb leg roasted with wild juniper, garlic, and mead glaze.",
		category: FOOD_CATEGORIES.DINNER,
	},
	{
		id: 26,
		name: "Skyr & Flatbread Platter",
		price: 9.99,
		image: getImage("skyr-flatbread"),
		description: "Icelandic skyr, pickled vegetables, and warm flatbread with herb butter.",
		category: FOOD_CATEGORIES.DINNER,
	},
	{
		id: 27,
		name: "Nordic Beetroot Hash",
		price: 8.79,
		image: getImage("beetroot-hash"),
		description: "Hearty hash of beets, onions, and potatoes with smoked salt and dill.",
		category: FOOD_CATEGORIES.DINNER,
	},
];
